Proyecto_ITI904_Equipo2/Controllers/MenuController.cs
using Proyecto_ITI904_Equipo2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_ITI904_Equipo2.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menu
        public ActionResult Index()
        {
            return View(db.Recetas.ToList());
        }
    }
}

Proyecto_ITI904_Equipo2/Controllers/RecetasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_ITI904_Equipo2.Models;
using Proyecto_ITI904_Equipo2.Models.Recetas;
using Proyecto_ITI904_Equipo2.Models.Ventas;
using CrystalDecisions.CrystalReports.Engine;
using Proyecto_ITI904_Equipo2.Views.Compras.ReportesCompras;
using CrystalDecisions.Shared;
using System.IO;

namespace Proyecto_ITI904_Equipo2.Controllers
{
    [Authorize(Roles = "Empleado,Admin")]
    public class RecetasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Recetas
        public async Task<ActionResult> Index()
        {
            return View(await db.Recetas.ToListAsync());
        }

        // GET: Recetas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receta receta = await db.Recetas.FindAsync(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        // GET: Recetas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recetas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "Id,Nombre,Instrucciones,TiempoPreparacionAlmacenado")] Receta receta)
        public async Task<ActionResult> Create(Receta receta)
        {
            foreach (var item in receta.Ingredientes)
            {
                item.Cantidad /= 1000;
            }

            var file = Request.Files[0];

            byte[] bytes = new byte[file.ContentLength];
            var i = file.InputStream.Read(bytes, 0, file.ContentLength);

            receta.Imagen = Convert.ToBase64String(bytes);

            if (ModelState.IsValid)
            {
                db.Recetas.Add(receta);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(receta);
        }

        // GET: Recetas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receta receta = await db.Recetas.FindAsync(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        // POST: Recetas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "Id,Nombre,Instrucciones,TiempoPreparacionAlmacenado")] Receta receta)
        public async Task<ActionResult> Edit(Receta receta)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in receta.Ingredientes)
                {
                    item.Cantidad /= 1000;
                }

                receta.Preparacion = db.TipoPreparacions.Find(receta.Preparacion_Id);

                db.Entry(receta).State = EntityState.Modified;

                foreach (var ingrediente in receta.Ingredientes.ToList())
                {
                    IngredienteDeReceta i; // Declaramos un ingrediente que nos ayudará en caso de tener que buscarlo
                    switch (ingrediente.Estatus)
                    {
                        case 'E':
                            /*
                             * Si el ingrediente esta marcado como editado lo buscamos en la base de datos e indicamos que fue editado
                             */
                            i = await db.IngredienteDeRecetas.FindAsync(ingrediente.Id);
                            db.Entry(i).State = EntityState.Modified;
                            break;
                        case 'D':
                            /*
                             * Si el ingrediente esta marcado como borrado lo buscamos en la base de datos e indicamos que fue borrado
                             */
                            if (ingrediente.Id == 0) break; // si el objeto fue borrado pero no tiene id nunca estuvo en la base de datos por lo que lo ignoramos
                            i = await db.IngredienteDeRecetas.FindAsync(ingrediente.Id);
                            db.Entry(i).State = EntityState.Deleted;
                            break;
                        case 'A':
                        default:
                            /*
                             * Si el producto fue agregado lo añadimos al schema. Si no se sabe cual es su estatus directamente asumimos
                             * que es nuevo
                             */
                            db.IngredienteDeRecetas.Add(ingrediente);
                            break;
                    }
                }

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(receta);
        }

        // GET: Recetas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receta receta = await db.Recetas.FindAsync(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        // POST: Recetas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Receta receta = await db.Recetas.FindAsync(id);
            db.Recetas.Remove(receta);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public ActionResult AddToCart(int id, int? cantidad = 1)
        {
            List<ProductoPreparado> productos = Session["ProductosPreparados"] as List<ProductoPreparado> ?? new List<ProductoPreparado>();

            ProductoPreparado producto = new ProductoPreparado() {
                RecetaBase_Id = id
            };

            Receta receta = db.Recetas.Find(id);
            foreach (IngredienteDeReceta i in receta.Ingredientes)
            {
                IngredienteDeProductoVendido newIng = new IngredienteDeProductoVendido
                {
                    Material_Id = i.Material_Id,
                    Cantidad = i.Cantidad,
                    Precio = i.Precio,
                    Costo = i.Costo
                };


                producto.Ingredientes.Add(newIng);
            }
            producto.RecetaBase = receta;

            db.Entry(receta).State = EntityState.Unchanged;

            producto.Cantidad = cantidad.Value;
            producto.Precio = receta.Precio;
            producto.Costo = receta.Costo;

            productos.Add(producto);

            Session["ProductosPreparados"] = productos;
            return RedirectToAction("Index", "Venta");
        }

        public async Task<ActionResult> LoadIngrediente(string name, int index, double? cantidad)
        {
            IngredienteDeReceta ing = new IngredienteDeReceta();
            ing.Id = 0;
            ing.Material = await db.Materiales.FirstOrDefaultAsync<Models.Inventario.Material>(x => x.Nombre == name);
            ing.Cantidad = cantidad ?? 1.0;

            ViewBag.Index = index;

            return PartialView("_IngredienteRecetaTR", ing);
        }

        public ActionResult ListMaterialsAsJSON()
        {
            return Json(db.Materiales.Select(x => x.Descripcion), JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        public ActionResult Reportes()
        {
            return View("_Reportes");

        }

        public ActionResult DescargarVentaProductos()
        {
            try
            {
                var rptH = new ReportClass();
                rptH.FileName = Server.MapPath("/Reportes/ReportesProductos/VentaProductos.rpt");
                rptH.Load();

                var connInfo = CrystalReportCnn.GetConnectionInfo();
                TableLogOnInfo logOnInfo = new TableLogOnInfo();
                Tables tables;
                tables = rptH.Database.Tables;
                foreach (Table table in tables)
                {
                    logOnInfo = table.LogOnInfo;
                    logOnInfo.ConnectionInfo = connInfo;
                    table.ApplyLogOnInfo(logOnInfo);
                }

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();

                Stream stream = rptH.ExportToStream(ExportFormatType.PortableDocFormat);
                rptH.Dispose();
                rptH.Close();

                return new FileStreamResult(stream, "application/pdf");
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

Proyecto_ITI904_Equipo2/Views/Menu/Index.cshtml
@model IEnumerable<Proyecto_ITI904_Equipo2.Models.Recetas.Receta>
@{
    ViewBag.Title = "Index";
}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Special Menu</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->
<!-- Start Menu -->
<div class="menu-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Nuestros productos</h2>
                    <p>Visita nuestra tienda para pedir tu café o cualquiera de nuestra mercancía</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="special-menu text-center">
                    <div class="button-group filter-button-group">
                        <button class="active" data-filter="*">Todos</button>
                        <button data-filter=".Espresso">Espressos</button>
                        <button data-filter=".Moka">Mokas</button>
                        <button data-filter=".Filtrado">Filtrados</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row special-list">
            @foreach (var item in Model)
            {
                Html.RenderPartial("_MenuRecipePartial", item);
            }
            @*<div class="col-lg-4 col-md-6 special-grid drinks">
                <div class="gallery-single fix">
                    <img src="~/images/CafeDeOlla.jpg" alt="Image" height="212" width="340">
                    <div class="why-text">
                        <h4>Cafe de olla</h4>
                        <p>
                            Un café muy tradicional. este cafe cuenta con la calidad que las personas les gusta
                            y tiene un sabor estupendo
                        </p>
                        <h5> $7.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid drinks">
                <div class="gallery-single fix">
                    <img src="~/images/Eiskaffee.jpg" alt="Image" height="215" width="340">
                    <div class="why-text">
                        <h4>Eiskaffee</h4>
                        <p>
                            Café creado en italia y se toma como una bebida fria, este café refresca mucho a las personas y la crema que
                            se añade muestra un sabor unico.
                        </p>
                        <h5> $9.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid drinks">
                <div class="gallery-single fix">
                    <img src="~/images/CafeIrlandes.jpg" alt="Image" height="215" width="340">
                    <div class="why-text">
                        <h4>Cafe Irlandes</h4>
                        <p>
                            Café con una pequeña cantidad de whisky.Este es un cafe muy tracional por su combinacion con alcohol y cafe
                            sabores que son muy poco comunes de encontrar
                        </p>
                        <h5> $10.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid lunch">
                <div class="gallery-single fix">
                    <img src="~/images/CafeTurco.jpg" alt="Image" height="215" width="340">
                    <div class="why-text">
                        <h4>Cafe turco</h4>
                        <p>
                            Café realizado en la forma tracional calentado en arena para obtener el sabor que lo caracteriza
                            Sin duda un cafe cambiara tus gustos.
                        </p>
                        <h5> $15.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid lunch">
                <div class="gallery-single fix">
                    <img src="~/images/Marocchino.jpg" alt="Image" height="215" width="340">
                    <div class="why-text">
                        <h4>Marocchino</h4>
                        <p>
                            Café tradicional italiano que se sirve con canela para dar un sabor dulce a la bebida.
                            Este café es de los mas tomados en italia.
                        </p>
                        <h5> $18.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid lunch">
                <div class="gallery-single fix">
                    <img src="~/images/CafeDeOlla2.jpg" alt="Image" height="215" width="340">
                    <div class="why-text">
                        <h4>Café de olla</h4>
                        <p>
                            Este café es muy tradicional en mexico, muchas personas acompañan este café con alguna pieza de pan para
                            endulzar mas su bebida.
                        </p>
                        <h5> $20.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid dinner">
                <div class="gallery-single fix">
                    <img src="~/images/Mazagran.jpg" alt="Image" height="215" width="340">
                    <div class="why-text">
                        <h4>Special Dinner 1</h4>
                        <p>
                            Café frio que muestra que se puede combinar el ron y el café de una forma que a las personas les agrade
                        </p>
                        <h5> $25.79</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 special-grid dinner">
                <div class="gallery-single fix">
                    <img src="~/images/img-07.jpg" class="img-fluid" alt="Image">
                    <div class="why-text">
                        <h4>Café bombón</h4>
                        <p>
                            es una mezcla de cafe con leche condenzada que deja ver de manera clara la distribución de estos dos elementos.
                            Este café hace honor a su nombre al parecer un bombón ingerible
                        </p>
                        <h5> $22.79</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 special-grid dinner">
                <div class="gallery-single fix">
                    <img src="~/images/img-08.jpg" class="img-fluid" alt="Image">
                    <div class="why-text">
                        <h4>Café affogato</h4>
                        <p>
                            Café frio que muestra que todo se puede combinar. este café incluye una bola de helado en su centro
                            y una cantidad de café que puede ser bebida o combinada con la gran cantidad de helado que poseé
                        </p>
                        <h5> $24.79</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 special-grid dinner">
                <div class="gallery-single fix">
                    <img src="~/images/img-09.jpg" class="img-fluid" alt="Image">
                    <div class="why-text">
                        <h4>Café americano</h4>
                        <p>
                            Si usted prefiere algo mas clasico y menos dulce este cafe es el adecuado para usted, un cafe tradicional americano
                        </p>
                        <h5> $24.79</h5>
                    </div>
                </div>
            </div>*@

        </div>
    </div>
</div>
<!-- End Menu -->
<!-- Start QT -->
<div class="qt-box qt-background">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto text-left">
                <p class="lead ">
                    Comparte la experiencia
                </p>
            </div>
        </div>
    </div>
</div>
<!-- End QT -->
<!-- Start Customer Reviews -->
@*<div class="customer-reviews-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Customer Reviews</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto text-center">
                <div id="reviews" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner mt-4">
                        <div class="carousel-item text-center active">
                            <div class="img-box p-1 border rounded-circle m-auto">
                                <img class="d-block w-100 rounded-circle" src="images/profile-1.jpg" alt="">
                            </div>
                            <h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Paul Mitchel</strong></h5>
                            <h6 class="text-dark m-0">Web Developer</h6>
                            <p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
                        </div>
                        <div class="carousel-item text-center">
                            <div class="img-box p-1 border rounded-circle m-auto">
                                <img class="d-block w-100 rounded-circle" src="images/profile-3.jpg" alt="">
                            </div>
                            <h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Steve Fonsi</strong></h5>
                            <h6 class="text-dark m-0">Web Designer</h6>
                            <p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
                        </div>
                        <div class="carousel-item text-center">
                            <div class="img-box p-1 border rounded-circle m-auto">
                                <img class="d-block w-100 rounded-circle" src="images/profile-7.jpg" alt="">
                            </div>
                            <h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Daniel vebar</strong></h5>
                            <h6 class="text-dark m-0">Seo Analyst</h6>
                            <p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#reviews" role="button" data-slide="prev">
                        <i class="fa fa-angle-left" aria-hidden="true"></i>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#reviews" role="button" data-slide="next">
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>*@
<!-- End Customer Reviews -->
<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +01 123-456-4590
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        contacto@congomate.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        Vicente Guerrero #415. Purisima del Rincón, Guanajuato
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->

Proyecto_ITI904_Equipo2/Views/Menu/_MenuRecipePartial.cshtml
@model Proyecto_ITI904_Equipo2.Models.Recetas.Receta

<div class="col-lg-4 col-md-6 special-grid drinks">
    <div class="gallery-single fix @Model.Preparacion.Nombre">
        @{ 
            string image;
            if (String.IsNullOrEmpty(Model.Imagen))
            {
                image = Url.Content("~/images/img-not-found.jpg");
            }
            else
            {
                image = "data:image/jpg; base64," + Model.Imagen;
            }
        }
        <img src="@image" class="img-fluid" alt="Imagen">
        <a class="why-text" href="@Url.Action("Details","Recetas",new { id = Model.Id})">
            <h4>@Model.Nombre</h4>
            <p></p>
            <h5> $@Model.Precio</h5>
        </a>
    </div>
</div>