Proyecto_ITI904_Equipo2/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNet.Identity;
using Proyecto_ITI904_Equipo2.Models;
using Proyecto_ITI904_Equipo2.Models.Compras;
using Proyecto_ITI904_Equipo2.Models.Inventario;
using Proyecto_ITI904_Equipo2.Views.Compras.ReportesCompras;

namespace Proyecto_ITI904_Equipo2.Controllers
{
    [Authorize(Roles = "Empleado,Admin")]
    public class ComprasController : Controller
    {
        public List<Material> Materiales;
        public List<int> ListaMateriales;
        public List<int> Cantidades;
        public List<double> Costos;
        public double subTotal = 0;
        public double totalCompra = 0;
        private ApplicationDbContext db = new ApplicationDbContext();


        #region Metodos generados por default
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Compra compra = db.Compras.Find(id);

            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = db.Compras.Find(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Recibida,FechaSolicitud,FechaRecepción,Proveedor_Id,Encargado_Id")] Compra compra, DateTime? FechaSolicitada)
        {
            if (ModelState.IsValid)
            {
                if (compra.Recibida == true)
                {
                    var vistaDetalleCompras = db.Database.SqlQuery<DetalleCompra>("Select * from DetalleCompras where Compra_Id = " + compra.Id);
                    var modeloDetalleCompras = vistaDetalleCompras.ToList();
                    List<Material> modeloMateriales = new List<Material>();
                    for (int i = 0; i < modeloDetalleCompras.Count; i++) {
                        var vistaMateriales = db.Database.SqlQuery<Material>("Select * from Materials where Id = " + modeloDetalleCompras[i].Material_Id);
                        modeloMateriales.Add(vistaMateriales.ToList()[0]);
                    }

                    for (int i = 0; i < modeloMateriales.Count; i++)
                    {
                        db.Database.ExecuteSqlCommand("UPDATE Materials SET " +
                        "Existencia = " + (modeloMateriales[i].Existencia + (modeloDetalleCompras[i].Cantidad * Convert.ToDouble(modeloMateriales[i].Contenido))) + "" +
                        "where Id = " + modeloMateriales[i].Id + "");
                        db.SaveChanges();
                    }

                    compra.FechaRecepción = Convert.ToDateTime(FechaSolicitada);
                    compra.Estatus = true;
                    db.Entry(compra).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("MostrarCompras");
                }
                else
                {
                    db.Entry(compra).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("MostrarCompras");
                }   
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Compra compra = db.Compras.Find(id);

            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Compra compra = db.Compras.Find(id);

            if (ModelState.IsValid)
            {
                compra.Estatus = false;;
                db.Entry(compra).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MostrarCompras", new { mostrar = 0});
            }
            return View(compra);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion


        #region Métodos de vistas
        public ActionResult Index()
        { // Regresa los proveedores actuales en el sistema
            return View("Index");
        }

        public ActionResult MostrarProveedores()
        {
            var vista = db.Database.SqlQuery<Proveedor>("Select * from Proveedors where Estatus = 1");

            return PartialView("_MostrarProveedores", vista.ToList());
        }

        public ActionResult MostrarCompras(int? mostrar)
        {
            var comprasRealizadas = db.Database.SqlQuery<Compra>("Select * from Compras where Recibida = 1 and Estatus = 1");
            var comprasNoRealizadas = db.Database.SqlQuery<Compra>("Select * from Compras where Recibida = 0 and Estatus = 1");

            if (mostrar == 1)
            {
                ViewBag.Ocultar = 0;
                return View("_MostrarCompras", comprasNoRealizadas.ToList());
            }
            else
            {
                ViewBag.Ocultar = 1;
                return View("_MostrarCompras", comprasRealizadas.ToList());
            }

            
        }

        public ActionResult MostrarCarritoCompras(int? id)
        {
            if (Session["IdMaterialesAgregados"] == null && Session["TotalCompra"] == null &&
                Session["MaterialesAgregados"] == null)
            {
                return View("Index");
            }
            else
            {
                ViewBag.idProveedor = id;

                var costos = Session["Costos"] as List<double>;
                ViewBag.Costos = costos;

                var cantidades = Session["Cantidades"] as List<int>;
                ViewBag.Cantidades = cantidades;

                ViewBag.TotalCompras = Session["TotalCompra"];

                var materialesId = Session["IdMaterialesAgregados"] as List<int>;
                var materialesSeleccionados = db.Materiales.Where(x => materialesId.Contains(x.Id));
                Session["MaterialesAgregados"] = materialesSeleccionados; // Guardamos la lista de los materiales para usarlos al momento de crear los detalles de compra
                return View("_MostrarCarritoCompras", materialesSeleccionados.ToList());
            }
        }

        public ActionResult MostrarDetCompra(int? id)
        {
            var listaDetCompra = db.Database.SqlQuery<DetalleCompra>("Select * from DetalleCompras where Compra_Id = " + id + "");
            var modeloListaDetCompra = listaDetCompra.ToList();
            double total = 0;
            List<double> importe = new List<double>();
            for (int i = 0; i < modeloListaDetCompra.Count; i++)
            {
                var listaMaterial = db.Database.SqlQuery<Material>("Select * from Materials where Id = " + modeloListaDetCompra[i].Material_Id);
                modeloListaDetCompra[i].Material = listaMaterial.ToList()[0];
                importe.Add(modeloListaDetCompra[i].Costo * modeloListaDetCompra[i].Cantidad);
                total += importe[i];
            }
            ViewBag.Importe = importe;
            ViewBag.Total = total;
            return PartialView("_MostrarDetCompra", modeloListaDetCompra.ToList());
        }
        #endregion


        #region Funcionalidad de Nueva Compra
        public ActionResult MostrarProveedoresMateriales(int? id, int? idM, int? cantidad, string btnOpcion, double? costoMaterial)
        {
            if (Session["IdProveedor"] == null && id == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (cantidad == null && idM == null && costoMaterial == null)
                { // Visualización
                    
                    var listaProvMate = db.Database.SqlQuery<ProveedorMaterials>("Select * from ProveedorMaterials where Proveedor_Id = " + id + "");
                    // Condicional 2.1 Verifica si la consulta regresó Ids o no
                    if (listaProvMate.Count() == 0)
                    { // Regresa la vista cuando no tienen datos
                        return View("_MostrarProveedoresMateriales");
                    }
                    else
                    { // Regresa los materiales que tenga el proveedor
                        int[] Materiales = new int[listaProvMate.Count()]; // Arreglo que guardará los Id
                        int val = 0;

                        foreach (var item in listaProvMate)
                        { // Guardar los ID de materiales del proveedor
                            Materiales[val] = item.Material_Id;
                            val++;
                        }

                        Session["IdProveedor"] = id;
                        ViewBag.idProveedor = Session["IdProveedor"];
                        ViewBag.Agregados = Session["IdMaterialesAgregados"]; // Se usa para decirle a la vista que datos están en el carrito ya agregados, si no hay ninguno

Proyecto_ITI904_Equipo2/Controllers/EquipoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_ITI904_Equipo2.Controllers
{
    public class EquipoController : Controller
    {
        // GET: Equipo
        public ActionResult Index()
        {
            return View();
        }
    }
}

Proyecto_ITI904_Equipo2/Controllers/GaleriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_ITI904_Equipo2.Controllers
{
    public class GaleriaController : Controller
    {
        // GET: Galeria
        public ActionResult Index()
        {
            return View();
        }
    }
}

Proyecto_ITI904_Equipo2/Controllers/MenuController.cs
using Proyecto_ITI904_Equipo2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_ITI904_Equipo2.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menu
        public ActionResult Index()
        {
            return View(db.Recetas.ToList());
        }
    }
}

Proyecto_ITI904_Equipo2/Views/Shared/_AboutAbstract.cshtml
@*
    HACK para cambiar globalmente la versión de Acerca de Nosotros modificarlo aqui
    Se recomienda no exceder de 1 parrafo con 240 caracteres para no romper con el
    esquema del documento.
*@
<p>
Congo Mate surge debido a que muchas de las personas ahora consumen café en
distintas horas, en distintos climas, pero suelen solo conocer un tipo
de café y no se tienen el suficiente conocimiento sobre este tipo de café.
</p>

Proyecto_ITI904_Equipo2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>Congo Mate - Café a tu manera</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="@Url.Content("~/images/favicon.ico")" type="image/x-icon">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="~/Content/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="~/Content/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Content/custom.css">
    @Styles.Render("~/bundles/jquery_ui/base")
    <style type="text/css">
        .congo-cart {
            display: block;
            text-indent: -9999px;
            width: 100px;
            height: 82px;
            background: url(/images/icon_cart.svg);
            background-size: 100px 82px;
        }
        .btn-sm {
            padding: 5px 10px;
            font-size: 12px;
            line-height: 1.5;
            border-radius: 3px
        }
    </style>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Start header -->
    <header class="top-navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="@Url.Content("~/images/logo.png")" alt="" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbars-rs-food">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">@Html.ActionLink("Menú", "Index", "Menu", null, new { @class = "nav-link" })</li>
                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Otros sitios</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                @Html.ActionLink("Reservación", "Index", "Home", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Stuff", "Index", "Equipo", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Galería", "Index", "Galeria", null, new { @class = "dropdown-item" })
                            </div>
                        </li>*@
                        @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Blog</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                    <a class="dropdown-item" href="blog.html">blog</a>
                                    <a class="dropdown-item" href="blog-details.html">blog Single</a>
                                </div>
                            </li>*@
                        <li class="nav-item">@Html.ActionLink("Contáctanos", "Index", "Contacto", null, new { @class = "nav-link" })</li>
                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- End header -->
    <!-- Start Sidebar -->
    @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Empleado")))
    {
        <div class="area"></div>
        <nav class="main-menu">
            <ul>
                <li>
                    <a href="@Url.Action("Index","Venta")">
                        <i class="fa fa-money fa-lg"></i>
                        <span class="nav-text">Ventas</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Compras")">
                        <i class="fa fa-shopping-bag fa-lg"></i>
                        <span class="nav-text">Compras</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Recetas")">
                        <i class="fa fa-list-ol fa-lg"></i>
                        <span class="nav-text">Recetas</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Materiales")">
                        <i class="fa fa-shopping-basket fa-lg"></i>
                        <span class="nav-text">Inventario</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Proveedores")">
                        <i class="fa fa-truck fa-lg"></i>
                        <span class="nav-text">Proveedores</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Users")">
                        <i class="fa fa-users fa-lg"></i>
                        <span class="nav-text">Usuarios</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("UnderContruction","Home")">
                        <i class="fa fa-lg fa-"></i>
                    </a>
                </li>
            </ul>
        </nav>
        @*<div id="mySidenav" class="sidenav">
                @Html.ActionLink("Ventas", "Index", "Venta", null, null)
                @Html.ActionLink("Compras", "Index", "Compras", null, null)
                @Html.ActionLink("Recetas", "Index", "Recetas", null, null)
                @Html.ActionLink("Inventario","Index", "Materiales", null, null)
                @Html.ActionLink("Proveedores", "Index", "Proveedores", null, null)
            </div>*@

    }
    <!-- End Sidebar -->

    <div class="container body-content">
        <div class="main-render-body">
            @RenderBody()
        </div>
        <hr />


        <!-- Start Footer -->
        <footer class="footer-area bg-f">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <h3>Acerca de CongoMate</h3>
                        @Html.Partial("_AboutAbstract")
                    </div>
                    <div class="col-lg-2 col-md-6">
                        <h3>Horarios</h3>
                        @*<p><span class="text-color">Monday: </span>Closed</p>*@
                        <p><span class="text-color">Lunes a Viernes :</span> 10:Am - 10:Pm</p>
                        <p><span class="text-color">Sábado:</span> 8:Am - 10:Pm</p>
                        <p><span class="text-color">Domingo :</span> 8:Am - 4:Pm</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h3>Información de contacto</h3>
                        <p class="lead">Vicente Guerrero, Purísima del Rincón, Gto, México, 36414</p>
                        <p class="lead"><a href="#">+01 2000 800 9999</a></p>
                        <p><a href="#"> administrativo@congomate.com</a></p>
                    </div>
                    <div class="col-lg-3 col-md-5">
                        <h3>Suscríbete</h3>
                        <div class="subscribe_form">
                            <form class="subscribe_form">
                                <input name="EMAIL" id="subs-email" class="form_input" placeholder="Correo electrónico... " type="email">
                                <button type="submit" class="submit">Suscribete</button>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                        @*<ul class="list-inline f-social">
                                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            </ul>*@
                    </div>
                </div>
            </div>

            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="company-name">
                                Todos los derechos reservados. &copy; @DateTime.Now.Year <a href="#">CongoMate</a>@*<a href="https://html.design/">html design</a>*@
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </footer>
        <!-- End Footer -->

        <a href="#" id="back-to-top" title="Volver arriba" style="display: none;">&uarr;</a>

        <!-- ALL JS FILES -->
        <script src="~/Scripts//jquery-3.2.1.min.js"></script>
        <script src="~/Scripts//popper.min.js"></script>
        <script src="~/Scripts//bootstrap.min.js"></script>
        <!-- ALL PLUGINS -->
        <script src="~/Scripts/jquery.superslides.min.js"></script>
        <script src="~/Scripts//images-loded.min.js"></script>
        <script src="~/Scripts//isotope.min.js"></script>
        <script src="~/Scripts//baguetteBox.min.js"></script>
        <script src="~/Scripts//form-validator.min.js"></script>
        <script src="~/Scripts//contact-form-script.js"></script>
        <script src="~/Scripts//custom.js"></script>
        @RenderSection("Scripts", false)
    </div>
</body>
</html>